virtualServices:
  - name: "adminv2-backdoor"
    hosts: 
      - "lava-admin.backdoor.demo2.lava.landadmin.com"
    gateways: 
      - "istio-system/internal-gateway"
    route:
      - destination:
          host: "adminv2"
          port:
            number: 80
  - name: "agentv2-backdoor"
    hosts: 
      - "agent.backdoor.demo2.lava.landadmin.com"
    gateways: 
      - "istio-system/internal-gateway"
    route:
      - destination:
          host: "agentv2"
          port:
            number: 80
  - name: "examiner-workbench-backdoor"
    hosts: 
      - "workbench.backdoor.demo2.lava.landadmin.com"
    gateways: 
      - "istio-system/internal-gateway"
    route:
      - destination:
          host: "examiner-workbench"
          port:
            number: 80
  - name: "tenant-adminv2-backdoor"
    hosts: 
      - "tenant-admin.backdoor.demo2.lava.landadmin.com"
    gateways: 
      - "istio-system/internal-gateway"
    route:
      - destination:
          host: "tenant-adminv2"
          port:
            number: 80
